name: Bug Report
description: Report a bug or problem with the project.
title: "[Bug] <short description of the problem>"
labels: [bug]
assignees: [Xentraxx]

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Please fill out *all* fields below. Incomplete issues will be closed.**

  - type: input
    id: gpht-version
    attributes:
      label: What version of GPTH are you using?
      placeholder: e.g. v5.0.6
    validations:
      required: true

  - type: input
    id: flag-combo
    attributes:
      label: What flag combination did you use?
      placeholder: e.g. --fix-extensions=standard --transform-pixel-mp
    validations:
      required: true

  - type: dropdown
    id: exiftool-installed
    attributes:
      label: Is Exiftool installed?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: current-result
    attributes:
      label: What is the current output/result?
      description: Please describe the problem and the current outcome.
      placeholder: I did this... and got this...
    validations:
      required: true

  - type: textarea
    id: expected-result
    attributes:
      label: What is the expected output/result?
      description: Please describe what you expected to happen.
      placeholder: I expected this... to happen...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. Los will greatly help us to diagnose the issue.
      render: shell
    validations:
      required: true

  - type: textarea
    id: more-info
    attributes:
      label: Further information on the issue
      description: Add any other relevant context or screenshots.
      placeholder: Any other details that could help reproduce the issue.
